import sqlite3
import re
from typing import Any

def _clamp_score(score: float) -> float:
    """Validator constraint: score must be STRICTLY between (0.01, 0.99)"""
    return float(max(0.001, min(0.999, score)))

def grade_task1(db: sqlite3.Connection, state: Any) -> float:
    main_table = state.table_registry["main"]
    id_col = state.column_registry["id"]
    
    initial_rows = state.initial_snapshot.get(main_table, [])
    initial_nulls = sum(1 for row in initial_rows if row.get(id_col) is None)
    initial_valid = sum(1 for row in initial_rows if row.get(id_col) is not None)
    
    cursor = db.cursor()
    try:
        cursor.execute(f"SELECT COUNT(*) FROM {main_table} WHERE {id_col} IS NULL")
        current_nulls = cursor.fetchone()[0]
        
        cursor.execute(f"SELECT COUNT(*) FROM {main_table} WHERE {id_col} IS NOT NULL")
        current_valid = cursor.fetchone()[0]
    except (sqlite3.OperationalError, sqlite3.DatabaseError):
        return _clamp_score(0.0)
        
    if initial_nulls == 0:
        null_score = 1.0
    else:
        null_score = 1.0 - (current_nulls / initial_nulls)
        
    if initial_valid == 0:
        destruction_penalty = 0.0
    else:
        destruction_penalty = max(0.0, (initial_valid - current_valid) / initial_valid)
        
    final_score = null_score - destruction_penalty
    return _clamp_score(final_score)

def _is_valid_masked_email(email: str) -> bool:
    """Email must keep first char, use asterisks for local part, preserve @domain, and match original structure."""
    return bool(re.match(r'^[a-zA-Z]\*+@[\w.\-]+\.\w+$', str(email)))

def grade_task2(db: sqlite3.Connection, state: Any) -> float:
    main_table = state.table_registry["main"]
    email_col = state.column_registry["email"]
    phone_col = state.column_registry["phone"]
    ssn_col = state.column_registry.get("ssn_col")

    cursor = db.cursor()
    try:
        if ssn_col:
            cursor.execute(f"SELECT {email_col}, {phone_col}, {ssn_col} FROM {main_table}")
        else:
            cursor.execute(f"SELECT {email_col}, {phone_col} FROM {main_table}")
        rows = cursor.fetchall()
    except (sqlite3.OperationalError, sqlite3.DatabaseError):
        return _clamp_score(0.0)

    if not rows:
        return _clamp_score(0.0)

    email_scores, phone_scores, ssn_scores = [], [], []

    for row in rows:
        row_vals = list(row)
        email = str(row_vals[0]) if row_vals[0] is not None else ""
        phone = str(row_vals[1]) if row_vals[1] is not None else ""

        email_scores.append(1.0 if _is_valid_masked_email(email) else 0.0)
        phone_scores.append(1.0 if re.match(r'^\*{3}-\*{3}-\d{4}$', phone) else 0.0)

        if ssn_col and len(row_vals) > 2:
            ssn = str(row_vals[2]) if row_vals[2] is not None else ""
            ssn_scores.append(1.0 if re.match(r'^\*{3}-\*{2}-\d{4}$', ssn) else 0.0)

    email_mean = sum(email_scores) / len(email_scores) if email_scores else 0.0
    phone_mean = sum(phone_scores) / len(phone_scores) if phone_scores else 0.0

    if ssn_scores:
        ssn_mean = sum(ssn_scores) / len(ssn_scores)
        return _clamp_score((email_mean + phone_mean + ssn_mean) / 3.0)
    else:
        return _clamp_score((email_mean + phone_mean) / 2.0)

def grade_task3(db: sqlite3.Connection, state: Any) -> float:
    try:
        view_name = state.table_registry.get("view_name", "executive_dashboard")
        cursor = db.execute(f"SELECT * FROM {view_name} ORDER BY id LIMIT 200")
        rows = cursor.fetchall()
        col_names = [d[0].lower() for d in cursor.description]

        expected_cols_logical = [c.lower() for c in state.initial_snapshot["expected_view_columns"]]
        expected_data = state.initial_snapshot["expected_view_data"]  # list of dicts, keyed by real DB col names

        if not rows:
            return _clamp_score(0.0)

        # Build logical→real key mapping from the first fixture row
        # expected_view_columns = ["id","product_name","revenue","category"]
        # expected_view_data[0] = {"id":1, "product_name":"...", "rev_jig":31.29, "category":"B"}
        # We align by POSITION (the fixture was generated by SELECT a.id, a.product_name, a.{new_col} AS revenue, b.category)
        fixture_keys = list(expected_data[0].keys()) if expected_data else []  # real DB keys in fixture order
        # Map: logical alias -> real fixture key
        logical_to_fixture = {expected_cols_logical[i]: fixture_keys[i] for i in range(min(len(expected_cols_logical), len(fixture_keys)))}

        # Result col names are whatever the agent's VIEW has
        # We match logical col names to result col names by exact string match (agent uses AS aliases)
        # Column match: order-agnostic — which logical cols appear in result?
        common_logical = set(expected_cols_logical) & set(col_names)
        col_score = len(common_logical) / len(expected_cols_logical) if expected_cols_logical else 0.0

        if col_score == 0.0:
            return _clamp_score(0.0)

        # Build result dicts keyed by lowercased col name
        result_dicts = [dict(zip(col_names, row)) for row in rows]

        # Sort both by "id" for stable row-by-row comparison
        sort_key_result = "id" if "id" in col_names else col_names[0]
        sort_key_fixture = logical_to_fixture.get("id", fixture_keys[0]) if fixture_keys else None

        result_sorted = sorted(result_dicts, key=lambda r: r.get(sort_key_result, 0))
        fixture_sorted = sorted(expected_data, key=lambda r: r.get(sort_key_fixture, 0)) if sort_key_fixture else expected_data

        if len(result_sorted) != len(fixture_sorted):
            row_ratio = min(len(result_sorted), len(fixture_sorted)) / max(len(fixture_sorted), 1)
            value_score = row_ratio * 0.5
        else:
            matches = 0
            total = 0
            for res_row, fix_row in zip(result_sorted, fixture_sorted):
                for logical in common_logical:
                    real_key = logical_to_fixture.get(logical, logical)
                    total += 1
                    res_val = str(res_row.get(logical, "")).strip()
                    fix_val = str(fix_row.get(real_key, "")).strip()
                    if res_val == fix_val:
                        matches += 1
            value_score = matches / total if total > 0 else 0.0

        return _clamp_score(0.3 * col_score + 0.7 * value_score)

    except Exception:
        return _clamp_score(0.0)
